# Generated by Django 6.0.3 on 2026-03-19 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Nom de l'organisation")),
                ('slug', models.SlugField(help_text='Identifiant unique (ex: acme-corp)', max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, verbose_name='Email de contact entreprise')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
                ('network_name', models.CharField(default='Mon Réseau', max_length=100)),
                ('network_latitude', models.FloatField(default=0.0)),
                ('network_longitude', models.FloatField(default=0.0)),
                ('network_address', models.CharField(blank=True, help_text='Adresse physique du siège / datacenter', max_length=200)),
                ('sector', models.CharField(choices=[('banking', 'Banque / Finance'), ('health', 'Santé'), ('industry', 'Industrie'), ('government', 'Gouvernement'), ('education', 'Éducation'), ('telecom', 'Télécommunications'), ('retail', 'Commerce / Distribution'), ('other', 'Autre')], default='other', max_length=20)),
                ('plan', models.CharField(choices=[('free', 'Gratuit'), ('pro', 'Professionnel'), ('enterprise', 'Entreprise')], default='free', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_setup_done', models.BooleanField(default=False, help_text="Wizard d'onboarding complété")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisations',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='habilitation_level',
            field=models.IntegerField(choices=[(5, 'Niveau 5 — Accès total (Super Admin)'), (4, 'Niveau 4 — Administrateur Organisation'), (3, 'Niveau 3 — Manager SOC'), (2, 'Niveau 2 — Analyste SOC'), (1, 'Niveau 1 — Observateur')], default=2, help_text="Niveau d'habilitation de sécurité (1=Observateur, 5=Super Admin)"),
        ),
        migrations.AddField(
            model_name='user',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Compte verrouillé après trop de tentatives'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='poste',
            field=models.CharField(blank=True, help_text='Ex: Responsable SOC, Ingénieur réseau, RSSI', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Administrateur Mylo'), ('org_admin', 'Administrateur Organisation'), ('soc_manager', 'Manager SOC'), ('soc_analyst', 'Analyste SOC'), ('viewer', 'Observateur')], default='soc_analyst', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='accounts.organisation', verbose_name='Organisation'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, help_text='Sauvegardé en cas de suppression utilisateur', max_length=150)),
                ('action', models.CharField(choices=[('login', 'Connexion'), ('logout', 'Déconnexion'), ('login_failed', 'Tentative de connexion échouée'), ('alert_view', "Consultation d'alerte"), ('alert_status_update', 'Mise à jour statut alerte'), ('alert_feedback', 'Feedback River sur alerte'), ('ip_block', 'Blocage IP'), ('ip_unblock', 'Déblocage IP'), ('ip_whitelist', 'Whitelisting IP'), ('settings_update', 'Modification paramètres IDS'), ('user_create', 'Création utilisateur'), ('user_update', 'Modification utilisateur'), ('user_delete', 'Suppression utilisateur'), ('report_generate', 'Génération rapport'), ('report_export', 'Export données'), ('org_update', 'Modification organisation'), ('onboarding_complete', 'Onboarding complété')], max_length=30)),
                ('description', models.TextField(blank=True, help_text="Détails de l'action")),
                ('object_type', models.CharField(blank=True, help_text="Type d'objet concerné (Alert, IP, User...)", max_length=50)),
                ('object_id', models.CharField(blank=True, help_text="ID de l'objet concerné", max_length=50)),
                ('object_repr', models.CharField(blank=True, help_text="Représentation de l'objet", max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text="IP de l'utilisateur", null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('method', models.CharField(blank=True, help_text='GET, POST, PATCH...', max_length=10)),
                ('endpoint', models.CharField(blank=True, help_text='URL appelée', max_length=200)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Données supplémentaires (avant/après modification)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='accounts.organisation')),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journal d'audit",
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['organisation', '-timestamp'], name='accounts_au_organis_9c3bc3_idx'), models.Index(fields=['user', '-timestamp'], name='accounts_au_user_id_1110c4_idx'), models.Index(fields=['action', '-timestamp'], name='accounts_au_action_918219_idx')],
            },
        ),
    ]
