# Generated by ChatGPT on 2026-06-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_totp_enabled_user_totp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_must_change',
            field=models.BooleanField(default=False, help_text='Oblige l’utilisateur à changer son mot de passe au prochain login'),
        ),
    ]
