# Generated by Django 6.0.3 on 2026-06-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_password_must_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Connexion'), ('logout', 'Déconnexion'), ('login_failed', 'Tentative de connexion échouée'), ('alert_view', "Consultation d'alerte"), ('alert_status_update', 'Mise à jour statut alerte'), ('alert_feedback', 'Feedback River sur alerte'), ('wazuh_rule_unmapped', 'Rule ID Wazuh non mappé'), ('ip_block', 'Blocage IP'), ('ip_unblock', 'Déblocage IP'), ('ip_whitelist', 'Whitelisting IP'), ('settings_update', 'Modification paramètres IDS'), ('user_create', 'Création utilisateur'), ('user_update', 'Modification utilisateur'), ('user_delete', 'Suppression utilisateur'), ('report_generate', 'Génération rapport'), ('report_export', 'Export données'), ('org_update', 'Modification organisation'), ('onboarding_complete', 'Onboarding complété')], max_length=30),
        ),
    ]
