# Generated by Django 6.0.3 on 2026-03-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiverMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', models.FloatField(default=0)),
                ('total_learned', models.IntegerField(default=0)),
                ('dos_learned', models.IntegerField(default=0)),
                ('ddos_learned', models.IntegerField(default=0)),
                ('probe_learned', models.IntegerField(default=0)),
                ('r2l_learned', models.IntegerField(default=0)),
                ('u2r_learned', models.IntegerField(default=0)),
                ('brute_learned', models.IntegerField(default=0)),
                ('web_learned', models.IntegerField(default=0)),
                ('bot_learned', models.IntegerField(default=0)),
                ('infil_learned', models.IntegerField(default=0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
