# Generated by Django 6.0.3 on 2026-03-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_type', models.CharField(choices=[('Normal', 'Normal'), ('DoS', 'DoS'), ('DDoS', 'DDoS'), ('Probe', 'Probe'), ('R2L', 'R2L'), ('U2R', 'U2R'), ('BruteForce', 'BruteForce'), ('WebAttack', 'WebAttack'), ('Botnet', 'Botnet'), ('Infiltration', 'Infiltration')], max_length=20)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=20)),
                ('binary_confidence', models.FloatField()),
                ('attack_confidence', models.FloatField()),
                ('is_attack', models.BooleanField(default=True)),
                ('src_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('dst_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('protocol', models.CharField(blank=True, max_length=10)),
                ('src_bytes', models.FloatField(default=0)),
                ('dst_bytes', models.FloatField(default=0)),
                ('duration', models.FloatField(default=0)),
                ('features', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('new', 'Nouvelle'), ('investigating', 'En cours'), ('resolved', 'Résolue'), ('false_positive', 'Faux positif')], default='new', max_length=20)),
                ('action_taken', models.CharField(blank=True, max_length=100)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='BlacklistedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('blocked_by', models.CharField(default='manual', max_length=50)),
                ('alert_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhitelistedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
