# Generated by Django 6.0.3 on 2026-05-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idssettings',
            name='baseline_validated',
            field=models.BooleanField(default=False, help_text='Admin a validé la baseline manuellement'),
        ),
        migrations.AddField(
            model_name='idssettings',
            name='opnsense_api_key',
            field=models.CharField(blank=True, help_text='Clé API OPNsense', max_length=200),
        ),
        migrations.AddField(
            model_name='idssettings',
            name='opnsense_api_secret',
            field=models.CharField(blank=True, help_text='Secret API OPNsense', max_length=200),
        ),
        migrations.AddField(
            model_name='idssettings',
            name='opnsense_enabled',
            field=models.BooleanField(default=False, help_text='Activer le blocage automatique via OPNsense'),
        ),
        migrations.AddField(
            model_name='idssettings',
            name='opnsense_url',
            field=models.URLField(blank=True, default='https://172.16.1.1', help_text="URL de l'interface OPNsense"),
        ),
    ]
