# Generated by Django 6.0.3 on 2026-03-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDSSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binary_threshold', models.FloatField(default=0.5, help_text='Seuil binaire (prob. min pour déclarer une attaque)')),
                ('confidence_alert', models.FloatField(default=0.7, help_text="Confiance min pour alerte 'Nouvelle' (sinon 'À vérifier')")),
                ('threshold_dos', models.FloatField(default=0.65)),
                ('threshold_ddos', models.FloatField(default=0.6)),
                ('threshold_probe', models.FloatField(default=0.55)),
                ('threshold_r2l', models.FloatField(default=0.25)),
                ('threshold_u2r', models.FloatField(default=0.15)),
                ('threshold_bruteforce', models.FloatField(default=0.35)),
                ('threshold_webattack', models.FloatField(default=0.35)),
                ('threshold_botnet', models.FloatField(default=0.25)),
                ('threshold_infiltration', models.FloatField(default=0.2)),
                ('auto_block_enabled', models.BooleanField(default=False, help_text='Bloquer automatiquement les IP suspectes')),
                ('auto_block_threshold', models.FloatField(default=0.85, help_text='Score au-dessus duquel on bloque automatiquement')),
                ('auto_block_duration', models.IntegerField(default=3600, help_text='Durée du blocage automatique en secondes (3600 = 1h)')),
                ('river_enabled', models.BooleanField(default=True, help_text="Activer l'apprentissage en ligne River")),
                ('river_learn_threshold', models.FloatField(default=0.7, help_text='Confiance min pour que River apprenne automatiquement')),
                ('notif_enabled', models.BooleanField(default=False)),
                ('notif_telegram_token', models.CharField(blank=True, max_length=200)),
                ('notif_telegram_chat', models.CharField(blank=True, max_length=100)),
                ('notif_email', models.EmailField(blank=True, max_length=254)),
                ('notif_webhook_url', models.URLField(blank=True)),
                ('notif_min_severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium')], default='HIGH', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'IDS Settings',
                'verbose_name_plural': 'IDS Settings',
            },
        ),
    ]
