# Generated by Django 6.0.3 on 2026-05-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_idssettings_baseline_validated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idssettings',
            name='opnsense_url',
            field=models.URLField(blank=True, default='https://172.16.1.1', help_text='https://172.16.1.1'),
        ),
    ]
