# Generated by Django 6.0.3 on 2026-03-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_idssettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='idssettings',
            name='network_latitude',
            field=models.FloatField(default=0.0, help_text='Latitude du siège / datacenter'),
        ),
        migrations.AddField(
            model_name='idssettings',
            name='network_longitude',
            field=models.FloatField(default=0.0, help_text='Longitude du siège / datacenter'),
        ),
        migrations.AddField(
            model_name='idssettings',
            name='network_name',
            field=models.CharField(default='Mon Réseau', help_text='Nom du réseau surveillé (affiché sur la Threat Map)', max_length=100),
        ),
    ]
