# Generated by Django 6.0.3 on 2026-06-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_alter_idssettings_opnsense_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipbaseline',
            name='m2_bytes',
            field=models.FloatField(default=0.0, help_text='Accumulateur Welford pour la variance des bytes'),
        ),
        migrations.AddField(
            model_name='ipbaseline',
            name='m2_duration',
            field=models.FloatField(default=0.0, help_text='Accumulateur Welford pour la variance des durées'),
        ),
        migrations.AlterField(
            model_name='alertcorrelation',
            name='attack_types',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='alertcorrelation',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='alertcorrelation',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='alertcorrelation',
            name='first_alert_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='alertcorrelation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='alertcorrelation',
            name='last_alert_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='alertcorrelation',
            name='next_step_prediction',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='alertcorrelation',
            name='recommended_action',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='alertcorrelation',
            name='src_ip',
            field=models.GenericIPAddressField(db_index=True),
        ),
        migrations.AlterField(
            model_name='idssettings',
            name='baseline_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='idssettings',
            name='binary_threshold',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='idssettings',
            name='confidence_alert',
            field=models.FloatField(default=0.7),
        ),
        migrations.AlterField(
            model_name='idssettings',
            name='opnsense_api_key',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='idssettings',
            name='opnsense_api_secret',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='idssettings',
            name='opnsense_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='idssettings',
            name='opnsense_url',
            field=models.URLField(blank=True, default='https://172.16.1.1'),
        ),
        migrations.AlterField(
            model_name='ipbaseline',
            name='anomaly_score',
            field=models.FloatField(default=0.0, help_text='Score actuel (0=normal, >3=suspect, >5=critique)'),
        ),
        migrations.AlterField(
            model_name='ipbaseline',
            name='attack_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ipbaseline',
            name='avg_bytes_per_flow',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ipbaseline',
            name='avg_duration',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ipbaseline',
            name='avg_requests_per_min',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ipbaseline',
            name='baseline_established',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ipbaseline',
            name='is_suspicious',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ipbaseline',
            name='last_anomaly_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ipbaseline',
            name='typical_ports',
            field=models.JSONField(default=dict, help_text='Fréquence des ports destination : {port: count}'),
        ),
        migrations.AlterField(
            model_name='networklog',
            name='is_threat',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='networklog',
            name='log_timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='networklog',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='networklog',
            name='parsed_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='networklog',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='networklog',
            name='program',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='networklog',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='networklog',
            name='source_host',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='networklog',
            name='source_ip',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='networklog',
            name='threat_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='networklog',
            name='vlan_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='networklog',
            name='vlan_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='syslogsource',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='syslogsource',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='syslogsource',
            name='log_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='syslogsource',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='syslogsource',
            name='vlan_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='syslogsource',
            name='vlan_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
