# Generated by Django 6.0.3 on 2026-06-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_ipbaseline_m2_bytes_ipbaseline_m2_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='source',
            field=models.CharField(default='scapy', max_length=20),
        ),
    ]
