# Generated by Django 6.0.3 on 2026-06-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_alert_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='attack_type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('DoS', 'DoS'), ('DDoS', 'DDoS'), ('Probe', 'Probe'), ('R2L', 'R2L'), ('U2R', 'U2R'), ('BruteForce', 'BruteForce'), ('WebAttack', 'WebAttack'), ('Botnet', 'Botnet'), ('Infiltration', 'Infiltration'), ('PortScan', 'Port Scan'), ('Malware', 'Malware'), ('PrivilegeEscalation', 'Privilege Escalation'), ('Reconnaissance', 'Reconnaissance'), ('Suspicious', 'Suspicious')], max_length=20),
        ),
    ]
