# Generated by Django 6.0.3 on 2026-06-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_auditlog_action'),
        ('alerts', '0006_alter_alert_attack_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='wazuh_alert_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='alert',
            unique_together={('organisation', 'wazuh_alert_id')},
        ),
    ]
