# Generated by Django 6.0.3 on 2026-03-26 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_organisation_alter_user_options_user_avatar_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_email', models.EmailField(help_text='Email destinataire du rapport quotidien', max_length=254)),
                ('send_hour', models.PositiveSmallIntegerField(default=7, help_text="Heure d'envoi (0-23, UTC)")),
                ('send_minute', models.PositiveSmallIntegerField(default=0, help_text="Minute d'envoi (0-59)")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_config', to='accounts.organisation')),
            ],
            options={
                'verbose_name': 'Configuration rapport',
                'verbose_name_plural': 'Configurations rapports',
            },
        ),
    ]
